Repository sonia-auv/octopus-telemetry, pull requests merged in 2021-09, with the labels that each got.

#99 Added Docker image support for ARM architecture
  .github/workflows/master.yml
Labels: Priority: Low, Type: Enhancement

#103 Fix/power module
  .gitignore
  src/components/ToolbarModule.tsx
  src/components/image/AUV8_Top_filaire_transparent.png
  src/components/powermodule/CurrentSection.tsx
  src/components/powermodule/PowerModule.test.tsx
  src/components/powermodule/PowerModule.tsx
  src/components/powermodule/VoltageSection.tsx
  src/components/powermodule/powersection.css
Labels: Priority: High, Type: Bug

#104 fixed errors
  src/components/powermodule/CurrentSection.tsx
  src/components/powermodule/PowerSection.tsx
  src/components/powermodule/VoltageSection.tsx
Labels: Priority: Medium, Type: Bug
